// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpUmmUcAU6NSKVOysAXtYLlubV1r0IQ0',
    appId: '1:727963531798:web:690409eeb7e44fd4e51337',
    messagingSenderId: '727963531798',
    projectId: 'jira-auth-e7daf',
    authDomain: 'jira-auth-e7daf.firebaseapp.com',
    storageBucket: 'jira-auth-e7daf.firebasestorage.app',
    measurementId: 'G-ZYVQHGMPYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZzZQmiYW0h2UMB5N7ZPS6tP7RVimAlEA',
    appId: '1:727963531798:android:95c9c3b40baff0b0e51337',
    messagingSenderId: '727963531798',
    projectId: 'jira-auth-e7daf',
    storageBucket: 'jira-auth-e7daf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLgfdslQKQDJJ9nh_xCLrGRRtW3P2g7OE',
    appId: '1:727963531798:ios:575c29869663238ee51337',
    messagingSenderId: '727963531798',
    projectId: 'jira-auth-e7daf',
    storageBucket: 'jira-auth-e7daf.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLgfdslQKQDJJ9nh_xCLrGRRtW3P2g7OE',
    appId: '1:727963531798:ios:575c29869663238ee51337',
    messagingSenderId: '727963531798',
    projectId: 'jira-auth-e7daf',
    storageBucket: 'jira-auth-e7daf.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementTool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnpUmmUcAU6NSKVOysAXtYLlubV1r0IQ0',
    appId: '1:727963531798:web:14f361789bd029c2e51337',
    messagingSenderId: '727963531798',
    projectId: 'jira-auth-e7daf',
    authDomain: 'jira-auth-e7daf.firebaseapp.com',
    storageBucket: 'jira-auth-e7daf.firebasestorage.app',
    measurementId: 'G-LR5Q1EV8RW',
  );

}